FROM wbk--mern-playground__core:latest as builder
COPY ./frontend/sites/backroads-tourcompany-landingpage-site ./frontend/sites/backroads-tourcompany-landingpage-site
RUN yarn install
RUN yarn build:backroads-tourcompany-landingpage-site

FROM nginx:latest as prod
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log
COPY --from=builder /usr/src/app/frontend/sites/backroads-tourcompany-landingpage-site/dist /usr/share/nginx/html
COPY ./frontend/sites/backroads-tourcompany-landingpage-site/nginx/default.conf /etc/nginx/conf.d/default.conf