FROM wbk--mern-playground__core:latest as builder

COPY ./frontend/sites/backroads-tourcompany-landingpage-site ./frontend/sites/backroads-tourcompany-landingpage-site

ARG CONTAINER_PORT
ENV PORT=$CONTAINER_PORT

EXPOSE $CONTAINER_PORT

RUN yarn install

# NOTE: this script is available in the base image
CMD [ "yarn", "develop:backroads-tourcompany-landingpage-site"]