FROM wbk--mern-playground__core:latest as builder

COPY ./frontend/apps/select-dropdown-app-vite ./frontend/apps/select-dropdown-app-vite
COPY ./frontend/libraries/select-dropdown-app-cmp-library ./frontend/libraries/select-dropdown-app-cmp-library
COPY ./frontend/lsg-styles-generic ./frontend/lsg-styles-generic
COPY ./shared/foundation ./shared/foundation

ARG CONTAINER_PORT
ENV PORT=$CONTAINER_PORT

EXPOSE $CONTAINER_PORT

RUN yarn install

# build dependnecies
RUN yarn build:lsg-styles-generic
RUN yarn build:shared
RUN yarn build:select-dropdown-app-cmp-library

# build app
RUN yarn build:select-dropdown-app-vite

FROM nginx:latest as prod

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

COPY --from=builder /usr/src/app/frontend/apps/select-dropdown-app-vite/dist /usr/share/nginx/html

COPY ./frontend/apps/select-dropdown-app-vite/nginx/default.conf /etc/nginx/conf.d/default.conf