FROM wbk--mern-playground__core:latest as builder

COPY ./backend/api/emaily-user-feedback-api ./backend/api/emaily-user-feedback-api

RUN yarn install
RUN yarn build:emaily-user-feedback-api

FROM node:20-alpine as service

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/backend/api/emaily-user-feedback-api/package.json ./
COPY --from=builder /usr/src/app/backend/api/emaily-user-feedback-api/dist ./dist

RUN yarn install --production

CMD ["node", "./dist/bin/www.js"]