FROM wbk--mern-playground__core:latest as builder
COPY ./backend/api/events-showcase-api ./backend/api/events-showcase-api
RUN yarn install
RUN yarn build:events-showcase-api

FROM node:20-alpine as service
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/backend/api/events-showcase-api/package.json ./
COPY --from=builder /usr/src/app/backend/api/events-showcase-api/dist ./dist
RUN yarn install --production
CMD ["node", "./dist/bin/www.js"]