FROM nginx:latest

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

COPY ./backend/services/storage/dj-events-document-storage-service/src /usr/share/nginx/html

