---
version: '3.7'
networks:
    dummy-blog-network:
        driver: bridge
services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../../backend/middleware/simple-fe-only-spa-proxy
            dockerfile: prod.Dockerfile
        container_name: container-dummy-blog-proxy
        image: paulserbandev/dummy-blog-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/middleware/simple-fe-only-spa-proxy/default.prod.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - ui-react-spa
        networks:
            - dummy-blog-network

    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        container_name: ui-react-spa-container
        image: paulserbandev/dummy-blog-app
        volumes:
            - /usr/src/app/dist
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
            - ../../frontend/apps/dummy-blog-app:/usr/src/app # Mount the app directory to the container
        env_file:
            - ../../infrastructure/env/dummy-blog.compose.env
        networks:
            - dummy-blog-network
