---
networks:
    json-to-excel-network:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        container_name: json-to-excel-proxy-container
        build:
            context: ../../../
            dockerfile: ./backend/services/proxy/simple-fe-only-spa-proxy/Dockerfile.prod
        image: paulserbandev/json-to-excel-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/services/proxy/simple-fe-only-spa-proxy/default.prod.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - ui-react-spa
        networks:
            - json-to-excel-network

    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        container_name: ui-react-spa-container
        image: paulserbandev/json-to-excel-ui-react-spa
        build:
            context: ../../../
            dockerfile: ./frontend/apps/json-to-excel-app/Dockerfile.prod
        env_file:
            - ../../../infrastructure/env/json-to-excel.compose.env
        networks:
            - json-to-excel-network
