FROM wbk--mern-playground__core:latest as builder
COPY ./backend/services/ecommerce-monolith-mvc-service ./backend/service/ecommerce-monolith-mvc-service
RUN yarn install
RUN yarn build:ecommerce-monolith-mvc-service

FROM node:20-alpine as service

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/backend/services/ecommerce-monolith-mvc-service/package.json ./
COPY --from=builder /usr/src/app/backend/services/ecommerce-monolith-mvc-service/dist ./dist

RUN yarn install
RUN npm install pm2 -g

COPY --from=builder /usr/src/app/backend/services/ecommerce-monolith-mvc-service/dist ./dist
COPY --from=builder /usr/src/app/ecosystem.config.js .

CMD ["pm2-runtime", "ecosystem.config.js", "--env", "production"]