FROM wbk--mern-playground__core:latest as builder

COPY ./backend/cms/dj-events-cms ./backend/cms/dj-events-cms
COPY ./shared/foundation ./shared/foundation
# Installing libvips-dev for sharp Compatability
RUN apt-get update && apt-get install libvips-dev -y

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN yarn config set network-timeout 600000 -g && yarn install

RUN yarn build:shared
RUN yarn build:dj-events-cms

CMD ["yarn", "develop:dj-events-cms"]
