FROM wbk--mern-playground__core:latest as builder

COPY ./backend/cms/hello-strapi-cms ./backend/cms/hello-strapi-cms
# Installing libvips-dev for sharp Compatability
RUN apt-get update && apt-get install libvips-dev -y

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN yarn config set network-timeout 600000 -g && yarn install

RUN yarn build:hello-strapi-cms

CMD ["yarn", "develop:hello-strapi-cms"]
