FROM wbk--mern-playground__core:latest as builder
COPY ./backend/services/ssr/ecommerce-monolith-mvc-ssr-service ./backend/services/ssr/ecommerce-monolith-mvc-ssr-service
COPY ./backend/services/ssr/ecommerce-monolith-mvc-ssr-service/public ./backend/services/ssr/ecommerce-monolith-mvc-ssr-service/dist/public
COPY ./backend/services/ssr/ecommerce-monolith-mvc-ssr-service/src/views ./backend/services/ssr/ecommerce-monolith-mvc-ssr-service/dist/src/views
RUN yarn install
CMD [ "yarn",  "develop:ecommerce-monolith-mvc-ssr-service"]