FROM wbk--mern-playground__core:latest as builder
COPY ./backend/api/blog-w-comments-posts-api ./backend/api/blog-w-comments-posts-api
RUN yarn install
RUN yarn build:blog-w-comments-posts-api

FROM node:20-alpine as service

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/backend/api/blog-w-comments-posts-api/package.json ./
COPY --from=builder /usr/src/app/backend/api/blog-w-comments-posts-api/dist ./dist

RUN yarn install --production

CMD ["node", "./dist/bin/www.js"]