FROM wbk--mern-playground__core:latest as builder

COPY ./backend/api/blog-w-comments-query-api ./backend/api/blog-w-comments-query-api

RUN yarn install

CMD [ "yarn", "develop:blog-w-comments-query-api"]