---
networks:
    base-spa-fe-only-network:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        container_name: nginx-proxy-container
        build:
            context: ../../../ # set context to root of monorepo project
            dockerfile: ./backend/services/proxy/base-spa-fe-only-proxy/Dockerfile.dev
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/services/proxy/base-spa-fe-only-proxy/default.dev.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        networks:
            - base-spa-fe-only-network

    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        container_name: ui-react-spa-container
        build:
            context: ../../../ # set context to root of monorepo project
            dockerfile: .${UI_PROJECT_PATH}/Dockerfile.dev
        volumes:
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
            - /usr/src/app${UI_PROJECT_PATH}/node_modules # Avoids overwriting dist with local volume
            - ../../..${UI_PROJECT_PATH}:/usr/src/app${UI_PROJECT_PATH}/ # Mount the app directory to the container
        restart: unless-stopped
        networks:
            - base-spa-fe-only-network
