---
networks:
    fortunes-network:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../../backend/services/fortunes-proxy
            dockerfile: dev.Dockerfile
        container_name: container-fortunes-proxy
        image: paulserbandev/fortunes-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/services/fortunes-proxy/default.conf:/etc/nginx/conf.d/default.conf
            - ../../../backend/services/fortunes-proxy/logs:/var/log/nginx
        networks:
            - fortunes-network
    # ---------------------------------------------------------------------
    # | ExpressJS API                                                     |
    # ---------------------------------------------------------------------
    express-fortunes-api:
        build:
            context: ../../backend/api/fortunes-api
            dockerfile: dev.Dockerfile
        image: paulserbandev/fortunes-api
        container_name: container-fortunes-api
        # ensure that the CONTAINER user id and group id are the same as the HOST user id and group id
        # without this, the container will fail to write files to the host volume
        user: '${HOST_USER_ID}:${HOST_GROUP_ID}'
        restart: always
        volumes:
            - ../../backend/api/fortunes-api:/usr/src/app/
            - /usr/src/app/node_modules
        networks:
            - fortunes-network
