---
networks:
    form-user-list-network:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../../backend/middleware/simple-fe-only-spa-proxy
            dockerfile: dev.Dockerfile
        container_name: container-form-user-list-proxy
        image: paulserbandev/form-user-list-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/middleware/simple-fe-only-spa-proxy/default.dev.conf:/etc/nginx/conf.d/default.conf
        networks:
            - form-user-list-network

    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        container_name: ui-react-spa-container
        build:
            context: ../../frontend/apps/form-user-list-app
            dockerfile: dev.Dockerfile
        volumes:
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
            - ../../frontend/apps/form-user-list-app:/usr/src/app:delegated # Mount the app directory to the container
        networks:
            - form-user-list-network
