---
networks:
    ecommerce-arch-journey-monolith-network:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../../backend/services/proxy/express-monolith-web-service-proxy
            dockerfile: dev.Dockerfile
        container_name: container-ecommerce-arch-journey-monolith-proxy
        image: paulserbandev/ecommerce-arch-journey-monolith-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/services/proxy/express-monolith-web-service-proxy/default.dev.conf:/etc/nginx/conf.d/default.conf
        networks:
            - ecommerce-arch-journey-monolith-network
    # ---------------------------------------------------------------------
    # | ExpressJS Web Service                                              |
    # ---------------------------------------------------------------------
    express-monolith-web-service:
        build:
            context: ../../backend/services/ssr/ecommerce-arch-journey-monolith-ssr-service
            dockerfile: dev.Dockerfile
        image: paulserbandev/ecommerce-arch-journey-monolith-ssr-service
        container_name: container-ecommerce-arch-journey-monolith-ssr-service
        # ensure that the CONTAINER user id and group id are the same as the HOST user id and group id
        # without this, the container will fail to write files to the host volume
        user: '${HOST_USER_ID}:${HOST_GROUP_ID}'
        restart: always
        volumes:
            - ../../backend/services/ssr/ecommerce-arch-journey-monolith-ssr-service:/usr/src/app/
            - /usr/src/app/node_modules
        networks:
            - ecommerce-arch-journey-monolith-network
