---
networks:
    flowrise-site-network:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        container_name: container-flowrise-site-proxy
        build:
            context: ../../../
            dockerfile: ./backend/services/proxy/simple-ssr-service-proxy/Dockerfile.dev
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/services/proxy/simple-ssr-service-proxy/default.dev.conf:/etc/nginx/conf.d/default.conf
        networks:
            - flowrise-site-network

    # ---------------------------------------------------------------------
    # Next.js SSR Service
    # ---------------------------------------------------------------------
    ssr-service:
        container_name: nextjs-service-container
        build:
            context: ../../../
            dockerfile: ./backend/services/ssr/flowrise-ssr-service/Dockerfile.dev
        env_file:
            - ../../../infrastructure/env/flowrise-site.compose.env
            - ../../../.env
        ports:
            - '9999:9999'
        volumes:
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
            - /usr/src/app/backend/services/ssr/flowrise-ssr-service/node_modules
            - ../../../backend/services/ssr/flowrise-ssr-service:/usr/src/app/backend/services/ssr/flowrise-ssr-service # Mount the app directory to the container

        networks:
            - flowrise-site-network
