---
networks:
    ecommerce-monolith-mvc-network:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../../
            dockerfile: ./backend/middleware/ecommerce-monolith-mvc-proxy/Dockerfile.dev
        container_name: ecommerce-monolith-mvc-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/middleware/ecommerce-monolith-mvc-proxy/default.conf:/etc/nginx/conf.d/default.conf
            - ../../../backend/middleware/ecommerce-monolith-mvc-proxy/logs:/var/log/nginx
        networks:
            - ecommerce-monolith-mvc-network
    # ---------------------------------------------------------------------
    # | ExpressJS Web Service                                              |
    # ---------------------------------------------------------------------
    express-ecommerce-monolith-mvc-service:
        build:
            context: ../../../
            dockerfile: ./backend/services/ecommerce-monolith-mvc-service/Dockerfile.dev
        container_name: ecommerce-monolith-mvc-service
        restart: always
        volumes:
            - /usr/src/app/node_modules
            - /usr/src/app/backend/services/ecommerce-monolith-mvc-service/node_modules
            - ../../../backend/services/ecommerce-monolith-mvc-service:/usr/src/app/backend/services/ecommerce-monolith-mvc-service
            - ../../../backend/services/ecommerce-monolith-mvc-service/src/views:/usr/src/app/backend/services/ecommerce-monolith-mvc-service/dist/src/views
            - ../../../backend/services/ecommerce-monolith-mvc-service/public:/usr/src/app/backend/services/ecommerce-monolith-mvc-service/dist/public

        networks:
            - ecommerce-monolith-mvc-network
