---
networks:
    sidebar-and-modal-basic-network:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../../backend/middleware/sidebar-and-modal-basic-proxy
            dockerfile: dev.Dockerfile
        container_name: container-sidebar-and-modal-basic-proxy
        image: paulserbandev/sidebar-and-modal-basic-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/middleware/sidebar-and-modal-basic-proxy/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - sidebar-and-modal-basic-network

    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        container_name: ui-react-spa-container
        build:
            context: ../../frontend/apps/sidebar-and-modal-basic-app
            dockerfile: dev.Dockerfile
        volumes:
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
            - ../../frontend/apps/sidebar-and-modal-basic-app:/usr/src/app # Mount the app directory to the container
        networks:
            - sidebar-and-modal-basic-network
