---
networks:
    hello-wordpress-network:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Wordpress                                                          |
    # ---------------------------------------------------------------------
    wordpress:
        image: wordpress:${WORDPRESS_VERSION:-latest}
        build:
            context: ../../../ # set context to root of monorepo project
            dockerfile: ./backend/services/ssr/hello-wordpress-ssr-service/Dockerfile.dev
        container_name: ${COMPOSE_PROJECT_NAME:-wordpress}
        environment:
            - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_NAME:-wordpress}
            - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
            - WORDPRESS_DB_USER=${DATABASE_USER:-root}
            - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
        depends_on:
            - mysql
            - phpmyadmin
        restart: always
        ports:
            - ${WORDPRESS_PORT:-80}:80

    # ---------------------------------------------------------------------
    # | MySQL                                                             |
    # ---------------------------------------------------------------------
    mysql:
        image: mariadb:${MARIADB_VERSION:-latest}
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-password}
            - MYSQL_USER=${DATABASE_USER:-root}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD:-password}
            - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME:-wordpress}
        restart: always

    # ---------------------------------------------------------------------
    # | PhpMyAdmin                                                         |
    # ---------------------------------------------------------------------
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        restart: always
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
        depends_on:
            - mysql
