---
networks:
    rnd-react-query-n-tanstack-todo-list-network:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../../ # set context to root of monorepo project
            dockerfile: ./backend/services/proxy/simple-base-spa-proxy/Dockerfile.dev
        container_name: container-rnd-react-query-n-tanstack-todo-list-proxy
        image: paulserbandev/rnd-react-query-n-tanstack-todo-list-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/services/proxy/simple-base-spa-proxy/default.dev.conf:/etc/nginx/conf.d/default.conf
        networks:
            - rnd-react-query-n-tanstack-todo-list-network

    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        image: paulserbandev/rnd-react-query-n-tanstack-todo-list-ui
        container_name: ui-react-spa-container
        build:
            context: ../../../ # set context to root of monorepo project
            dockerfile: ./frontend/apps/rnd-react-query-n-tanstack-todo-list-app/Dockerfile.dev
        env_file:
            - ../../../infrastructure/env/rnd-react-query-n-tanstack-todo-list.compose.env
        volumes:
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
            - /usr/src/app/frontend/apps/rnd-react-query-n-tanstack-todo-list-app/node_modules # Avoids overwriting dist with local volume
            - ../../../frontend/apps/rnd-react-query-n-tanstack-todo-list-app:/usr/src/app/frontend/apps/rnd-react-query-n-tanstack-todo-list-app/ # Mount the app directory to the container
        restart: unless-stopped
        networks:
            - rnd-react-query-n-tanstack-todo-list-network

    # ---------------------------------------------------------------------
    # | Express.js (Node.js) API                                           |
    # ---------------------------------------------------------------------
    express-api:
        restart: always
        container_name: express-api-container
        build:
            context: ../../../
            dockerfile: ./backend/api/rnd-react-query-n-tanstack-todo-list-api/Dockerfile.dev
        env_file:
            - ../../../infrastructure/env/rnd-react-query-n-tanstack-todo-list.compose.env
            - ../../../.env
        volumes:
            - /usr/src/app/node_modules
            - /usr/src/app/backend/api/rnd-react-query-n-tanstack-todo-list-api/dist
            - /usr/src/app/backend/api/rnd-react-query-n-tanstack-todo-list-api/node_modules
            - ../../../backend/api/rnd-react-query-n-tanstack-todo-list-api:/usr/src/app/backend/api/rnd-react-query-n-tanstack-todo-list-api
        networks:
            - rnd-react-query-n-tanstack-todo-list-network
