---
networks:
    hello-strapi-cms:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Stratpi CMS Service
    # ---------------------------------------------------------------------
    hello-strapi-cms:
        container_name: hello-strapi-cms
        build:
            context: ../../../ # set context to root of monorepo project
            dockerfile: ./backend/cms/hello-strapi-cms/Dockerfile.dev
        ports:
            - '1337:1337'
        restart: unless-stopped
        env_file:
            - ../../../infrastructure/env/hello-strapi-cms.compose.env
            - ../../../.env
        environment:
            DATABASE_CLIENT: ${DATABASE_CLIENT}
            DATABASE_HOST: strapiDB
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PORT: ${DATABASE_PORT}
            JWT_SECRET: ${JWT_SECRET}
            ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            NODE_ENV: ${NODE_ENV}
        volumes:
            - /usr/src/app/node_modules
        #   - ./config:/opt/app/config
        #   - ./src:/opt/app/src
        #   - ./package.json:/opt/package.json
        #   - ./yarn.lock:/opt/yarn.lock # Replace with package-lock.json if using npm
        #   - ./.env:/opt/app/.env

        networks:
            - hello-strapi-cms
        depends_on:
            - strapiDB

        # ---------------------------------------------------------------------
        # | MariaDB Database Service
        # ---------------------------------------------------------------------
    strapiDB:
        container_name: strapiDB
        platform: linux/amd64 #for platform error on Apple M1 chips
        restart: unless-stopped
        env_file:
            - ../../../infrastructure/env/hello-strapi-cms.compose.env
            - ../../../.env
        image: mariadb:latest
        environment:
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
        volumes:
            - strapi-data:/var/lib/mysql
            #- ./data:/var/lib/mysql # if you want to use a bind folder
        ports:
            - '3306:3306'
        networks:
            - hello-strapi-cms

    phpmyadmin:
        depends_on:
            - strapiDB
        image: phpmyadmin/phpmyadmin:latest
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_HOST=strapiDB
            - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
        networks:
            - hello-strapi-cms

volumes:
    strapi-data:
