---
networks:
    minesweeper-game-network:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        container_name: minesweeper-game-proxy
        build:
            context: ../../../ # set context to root of monorepo project
            dockerfile: ./backend/services/simple-fe-only-spa-proxy/Dockerfile.dev
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/services/simple-fe-only-spa-proxy/default.dev.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        networks:
            - minesweeper-game-network

    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        container_name: ui-react-spa
        build:
            context: ../../../
            dockerfile: ./frontend/apps/minesweeper-game-app/Dockerfile.dev
        volumes:
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
            - /usr/src/app/frontend/apps/minesweeper-game-app/node_modules # Avoids overwriting dist with local volume
            - ../../../frontend/apps/minesweeper-game-app:/usr/src/app/frontend/apps/minesweeper-game-app # Mount the app directory to the container
        networks:
            - minesweeper-game-network
