---
networks:
    simple-shop-network:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        container_name: container-simple-shop-proxy
        image: paulserbandev/simple-shop-proxy
        build:
            context: ../../../ # set context to root of monorepo project
            dockerfile: ./backend/services/proxy/simple-base-spa-proxy/Dockerfile.dev
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/services/proxy/simple-base-spa-proxy/default.dev.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        networks:
            - simple-shop-network

    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        image: paulserbandev/simple-shop-ui
        container_name: ui-react-spa-container
        build:
            context: ../../../ # set context to root of monorepo project
            dockerfile: ./frontend/apps/simple-shop-app/Dockerfile.dev
        volumes:
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
            - /usr/src/app/frontend/apps/simple-shop-app/node_modules # Avoids overwriting dist with local volume
            - ../../../frontend/apps/simple-shop-app:/usr/src/app/frontend/apps/simple-shop-app/ # Mount the app directory to the container
        restart: unless-stopped
        networks:
            - simple-shop-network

    # ---------------------------------------------------------------------
    # | Express.js (Node.js) API                                           |
    # ---------------------------------------------------------------------
    express-api:
        restart: always
        container_name: express-api-container
        build:
            context: ../../../
            dockerfile: ./backend/api/simple-shop-api/Dockerfile.dev
        env_file:
            - ../../../infrastructure/env/simple-shop.compose.env
            - ../../../.env
        volumes:
            - /usr/src/app/node_modules
            - /usr/src/app/backend/api/simple-shop-api/dist
            - /usr/src/app/backend/api/simple-shop-api/node_modules
            - ../../../backend/api/simple-shop-api:/usr/src/app/backend/api/simple-shop-api
        networks:
            - simple-shop-network
