---
version: '3.7'
networks:
    rnd-react-query-n-tanstack-todo-list-network:
        driver: bridge
services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../../backend/middleware/full-stack-mock-proxy
            dockerfile: dev.Dockerfile
        container_name: container-rnd-react-query-n-tanstack-todo-list-proxy
        image: paulserbandev/rnd-react-query-n-tanstack-todo-list-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../../backend/middleware/full-stack-mock-proxy/default.dev.conf:/etc/nginx/conf.d/default.conf
        networks:
            - rnd-react-query-n-tanstack-todo-list-network

    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        container_name: ui-react-spa-container
        build:
            context: ../../frontend/apps/rnd-react-query-n-tanstack-todo-list-app
            dockerfile: dev.Dockerfile
        env_file:
            - ../../infrastructure/env/rnd-react-query-n-tanstack-todo-list.compose.env
        volumes:
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
            - ../../frontend/apps/rnd-react-query-n-tanstack-todo-list-app:/usr/src/app # Mount the app directory to the container
        networks:
            - rnd-react-query-n-tanstack-todo-list-network
        develop:
            watch:
                - action: sync
                  path: ../../frontend/apps/rnd-react-query-n-tanstack-todo-list-app
                  target: /*
                  ignore:
                      - ../../frontend/apps/rnd-react-query-n-tanstack-todo-list-app/node_modules
                - action: rebuild
                  path: ../../frontend/apps/rnd-react-query-n-tanstack-todo-list-app/package.json
                  target: /*

    # ---------------------------------------------------------------------
    # | ExpressJS API                                                     |
    # ---------------------------------------------------------------------
    express-api:
        build:
            context: ../../backend/api/rnd-react-query-n-tanstack-todo-list-api
            dockerfile: dev.Dockerfile
        image: paulserbandev/rnd-react-query-n-tanstack-todo-list-api
        container_name: container-rnd-react-query-n-tanstack-todo-list-api
        restart: always
        # ensure that the CONTAINER user id and group id are the same as the HOST user id and group id
        # without this, the container will fail to write files to the host volume
        user: '${HOST_USER_ID}:${HOST_GROUP_ID}'
        env_file:
            - ../../infrastructure/env/rnd-react-query-n-tanstack-todo-list.compose.env
            - ../../.env
        volumes:
            - /usr/src/app/node_modules
            - ../../backend/api/rnd-react-query-n-tanstack-todo-list-api:/usr/src/app/
        networks:
            - rnd-react-query-n-tanstack-todo-list-network
        develop:
            watch:
                - action: sync
                  path: ../../backend/api/rnd-react-query-n-tanstack-todo-list-api
                  target: /*
                  ignore:
                      - ../../backend/api/rnd-react-query-n-tanstack-todo-list-api/node_modules
                - action: rebuild
                  path: ../../backend/api/rnd-react-query-n-tanstack-todo-list-api/package.json
                  target: /*
