---
networks:
    hello-strapi-cms:
        driver: bridge

services:
    # ---------------------------------------------------------------------
    # | Stratpi CMS
    # ---------------------------------------------------------------------
    strapi-cms:
        container_name: ${COMPOSE_PROJECT_NAME}
        build:
            context: ../../../ # set context to root of monorepo project
            dockerfile: ./backend/cms/hello-strapi-cms/Dockerfile.dev
        ports:
            - '1337:1337'
        restart: unless-stopped
        env_file:
            - ../../../infrastructure/env/hello-strapi-cms.compose.env
            - ../../../.env
        environment:
            DATABASE_CLIENT: ${DATABASE_CLIENT}
            DATABASE_HOST: mariadb-database-service
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PORT: ${DATABASE_PORT}
            JWT_SECRET: ${JWT_SECRET}
            ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            NODE_ENV: ${NODE_ENV}
        volumes:
            - /usr/src/app/node_modules
            - ../../../backend/cms/hello-strapi-cms/config:/usr/src/app/backend/cms/hello-strapi-cms/config
            - ../../../backend/cms/hello-strapi-cms/src:/usr/src/app/backend/cms/hello-strapi-cms/src
            - ../../../backend/cms/hello-strapi-cms/public/uploads:/usr/src/app/backend/cms/hello-strapi-cms/public/uploads

        networks:
            - hello-strapi-cms
        depends_on:
            - mariadb-database-service

        # ---------------------------------------------------------------------
        # | MariaDB Database Service
        # ---------------------------------------------------------------------
    mariadb-database-service:
        container_name: ${COMPOSE_PROJECT_NAME}_mariadb-database-service
        platform: linux/amd64 #for platform error on Apple M1 chips
        restart: unless-stopped
        env_file:
            - ../../../infrastructure/env/hello-strapi-cms.compose.env
            - ../../../.env
        image: mariadb:latest
        environment:
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
        volumes:
            - hello-strapi-data:/var/lib/mysql
            - ../../../database/seeds/hello-strapi-cms-db/hello-strapi-cms.sql:/docker-entrypoint-initdb.d/hello-strapi-cms.sql
            # - ../../../database/.tmp-data/hello-strapi-db/:/var/lib/mysql # if you want to use a bind folder
        ports:
            - '3306:3306'
        networks:
            - hello-strapi-cms

    phpmyadmin-service:
        depends_on:
            - mariadb-database-service
        image: phpmyadmin/phpmyadmin:latest
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        platform: linux/amd64 #for platform error on Apple M1 chips
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mariadb-database-service
            - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
        networks:
            - hello-strapi-cms

volumes:
    hello-strapi-data:
