FROM wbk--mern-playground__core:latest as builder
COPY ./backend/api/rnd-react-query-n-tanstack-todo-list-api ./backend/api/rnd-react-query-n-tanstack-todo-list-api
RUN yarn install
RUN yarn build:rnd-react-query-n-tanstack-todo-list-api

FROM node:20-alpine as service

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/backend/api/rnd-react-query-n-tanstack-todo-list-api/package.json ./
COPY --from=builder /usr/src/app/backend/api/rnd-react-query-n-tanstack-todo-list-api/dist ./dist

RUN yarn install --production

CMD ["node", "./dist/bin/www.js"]