FROM wbk--mern-playground__core:latest as builder
COPY ./backend/services/ssr/ecommerce-shop-w-pug-ssr-service ./backend/services/ssr/ecommerce-shop-w-pug-ssr-service
RUN yarn install
RUN yarn build:ecommerce-shop-w-pug-ssr-service

FROM node:20-alpine as service

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/backend/services/ssr/ecommerce-shop-w-pug-ssr-service/package.json ./
COPY --from=builder /usr/src/app/backend/services/ssr/ecommerce-shop-w-pug-ssr-service/dist ./dist
COPY --from=builder /usr/src/app/backend/services/ssr/ecommerce-shop-w-pug-ssr-service/src/views ./dist/src/views
COPY --from=builder /usr/src/app/backend/services/ssr/ecommerce-shop-w-pug-ssr-service/public ./dist/public
COPY --from=builder /usr/src/app/backend/services/ssr/ecommerce-shop-w-pug-ssr-service/ecosystem.config.js .

RUN yarn install
RUN npm install pm2 -g

CMD ["pm2-runtime", "ecosystem.config.js", "--env", "production"]