FROM wbk--mern-playground__core:latest as builder

COPY ./backend/services/flowrise-ssr-service ./backend/services/flowrise-ssr-service

ARG CONTAINER_PORT
ENV PORT=$CONTAINER_PORT
EXPOSE $CONTAINER_PORT

RUN yarn install

CMD [ "yarn", "develop:flowrise-site"]