module.exports = {
    plugins: ['stylelint-scss'],
    extends: ['stylelint-config-sass-guidelines'],
    rules: {
        'color-function-notation': null,
        'at-rule-empty-line-before': null,
        'at-rule-no-vendor-prefix': true,
        'block-closing-brace-empty-line-before': null,
        'block-closing-brace-newline-after': null,
        'block-opening-brace-space-before': null,
        'color-named': 'never',
        'declaration-empty-line-before': null,
        'declaration-no-important': null,
        'font-family-name-quotes': 'always-where-recommended',
        'font-weight-notation': [
            'numeric',
            {
                ignore: ['relative'],
            },
        ],
        'function-url-no-scheme-relative': true,
        'function-url-quotes': 'always',
        'max-line-length': null,
        'media-feature-name-no-vendor-prefix': true,
        'no-descending-specificity': null,
        'property-no-vendor-prefix': true,
        'rule-empty-line-before': null,
        'selector-attribute-quotes': 'always',
        'selector-class-pattern': null,
        'selector-max-attribute': 2,
        'selector-max-class': 4,
        'selector-max-combinators': 4,
        'selector-max-compound-selectors': 4,
        'selector-max-id': 0,
        'selector-max-specificity': null,
        'selector-max-type': 2,
        'selector-max-universal': 1,
        'selector-no-vendor-prefix': true,
        'shorthand-property-no-redundant-values': true,
        'value-no-vendor-prefix': true,
        'at-rule-no-unknown': null,
        'no-invalid-position-at-import-rule': null,
        'scss/at-function-named-arguments': 'never',
        'scss/at-function-parentheses-space-before': 'never',
        'scss/at-import-no-partial-leading-underscore': true,
        'scss/at-import-partial-extension': 'always',
        'scss/at-mixin-argumentless-call-parentheses': 'always',
        'scss/at-mixin-named-arguments': null,
        'scss/at-mixin-parentheses-space-before': 'never',
        'scss/at-rule-no-unknown': true,
        'scss/dimension-no-non-numeric-values': true,
        'scss/dollar-variable-colon-space-after': 'at-least-one-space',
        'scss/dollar-variable-colon-space-before': 'never',
        'scss/dollar-variable-no-missing-interpolation': true,
        'scss/media-feature-value-dollar-variable': null,
        'scss/no-duplicate-dollar-variables': [
            null,
            {
                ignoreInsideAtRules: ['if', 'mixin'],
            },
        ],
        'scss/no-duplicate-mixins': true,
        'scss/operator-no-newline-after': true,
        'scss/operator-no-newline-before': true,
        'scss/operator-no-unspaced': true,
        'scss/selector-no-redundant-nesting-selector': true,
        'function-no-unknown': [
            true,
            {
                ignoreFunctions: [
                    'math.div',
                    'convert-rem',
                    'map-get',
                    'last-map-item',
                    'map.get',
                    'breakpoint-infix',
                    'breakpoint-prev',
                    'percentage',
                    'math.percentage',
                    'list.nth',
                    'if',
                    'meta.type-of',
                    'list.length',
                    'list.index',
                    'map.keys',
                    'map.merge',
                    'layer-index',
                ],
            },
        ],
    },
};
