# ----------------- BUILDER STAGE -----------------
FROM wbk--mern-playground__core:latest as builder
COPY ./frontend/apps/elegant-redux-online-shop-app ./frontend/apps/elegant-redux-online-shop-app
RUN yarn install
RUN yarn build:elegant-redux-online-shop-app

# ----------------- PRODUCTION STAGE -----------------
FROM nginx:latest as prod
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log
COPY --from=builder /usr/src/app/frontend/apps/elegant-redux-online-shop-app/dist /usr/share/nginx/html
COPY ./frontend/apps/elegant-redux-online-shop-app/nginx/default.conf /etc/nginx/conf.d/default.conf