FROM wbk--mern-playground__core:latest as builder
COPY ./frontend/apps/elegant-redux-online-shop-app ./frontend/apps/elegant-redux-online-shop-app
RUN yarn install
CMD [ "yarn", "develop:elegant-redux-online-shop-app"]