---
version: '3.7'
networks:
    fortunes-network:
        driver: bridge
services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../backend/services/fortunes-proxy
            dockerfile: dev.Dockerfile
        container_name: container-fortunes-proxy
        image: paulserbandev/fortunes-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../backend/services/fortunes-proxy/default.conf:/etc/nginx/conf.d/default.conf
            - ../../backend/services/fortunes-proxy/logs:/var/log/nginx
        networks:
            - fortunes-network
    # ---------------------------------------------------------------------
    # | ExpressJS API                                                     |
    # ---------------------------------------------------------------------
    express-fortunes-api:
        build:
            context: ../../backend/api/fortunes-api
            dockerfile: dev.Dockerfile
        image: paulserbandev/fortunes-api
        container_name: container-fortunes-api
        restart: always
        volumes:
            - ../../backend/api/fortunes-api:/usr/src/app/
            - /usr/src/app/node_modules
        networks:
            - fortunes-network
