---
version: '3.8'

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../backend/services/shopping-cart-redux-proxy
            dockerfile: dev.Dockerfile
        container_name: container-shopping-cart-redux-proxy
        image: paulserbandev/shopping-cart-redux-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../backend/services/shopping-cart-redux-proxy/default.conf:/etc/nginx/conf.d/default.conf
            - ../../backend/services/shopping-cart-redux-proxy/logs:/var/log/nginx
        networks:
            - shopping-cart-redux-network
    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        container_name: ui-react-spa-container
        build:
            context: ../../frontend/apps/shopping-cart-redux
            dockerfile: dev.Dockerfile
        # ports:
        #     - '3000:5173' # Expose the port your app runs on
        volumes:
            - ../../frontend/apps/shopping-cart-redux:/usr/src/app # Mount the app directory to the container
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
        networks:
            - shopping-cart-redux-network

networks:
    shopping-cart-redux-network:
        driver: bridge
