---
version: '3.7'
networks:
    ecommerce-arch-journey-monolith-network:
        driver: bridge
services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../backend/middleware/ecommerce-arch-journey-monolith-proxy
            dockerfile: dev.Dockerfile
        container_name: container-ecommerce-arch-journey-monolith-proxy
        image: paulserbandev/ecommerce-arch-journey-monolith-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../backend/middleware/ecommerce-arch-journey-monolith-proxy/default.conf:/etc/nginx/conf.d/default.conf
            - ../../backend/middleware/ecommerce-arch-journey-monolith-proxy/logs:/var/log/nginx
        networks:
            - ecommerce-arch-journey-monolith-network
    # ---------------------------------------------------------------------
    # | ExpressJS Web Service                                              |
    # ---------------------------------------------------------------------
    express-ecommerce-arch-journey-monolith-service:
        build:
            context: ../../backend/services/ecommerce-arch-journey-monolith-service
            dockerfile: dev.Dockerfile
        image: paulserbandev/ecommerce-arch-journey-monolith-service
        container_name: container-ecommerce-arch-journey-monolith-service
        restart: always
        volumes:
            - ../../backend/services/ecommerce-arch-journey-monolith-service:/usr/src/app/
            - /usr/src/app/node_modules
        networks:
            - ecommerce-arch-journey-monolith-network
