---
version: '3.8'

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../backend/services/spot-share-proxy
            dockerfile: dev.Dockerfile
        container_name: container-spot-share-proxy
        image: paulserbandev/spot-share-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../backend/services/spot-share-proxy/default.conf:/etc/nginx/conf.d/default.conf
            - ../../backend/services/spot-share-proxy/logs:/var/log/nginx

        networks:
            - spot-share-network
    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        container_name: ui-react-spa-container
        build:
            context: ../../frontend/apps/spot-share-app
            dockerfile: dev.Dockerfile
        volumes:
            - ../../frontend/apps/spot-share-app:/usr/src/app # Mount the app directory to the container
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
        env_file:
            - ../../infrastructure/env/spot-share.compose.env
        networks:
            - spot-share-network

    # ---------------------------------------------------------------------
    # | ExpressJS API                                                     |
    # ---------------------------------------------------------------------
    express-spot-share-api:
        build:
            context: ../../backend/api/spot-share-api
            dockerfile: dev.Dockerfile
        image: paulserbandev/spot-share-api
        container_name: container-spot-share-api
        restart: always
        env_file:
            - ../../infrastructure/env/spot-share.compose.env
            - ../../.env
        volumes:
            - ../../backend/api/spot-share-api:/usr/src/app/
            - /usr/src/app/node_modules
        networks:
            - spot-share-network
    # ---------------------------------------------------------------------
    # | MongoDB Database Server                                            |
    # ---------------------------------------------------------------------

    mongo1:
        container_name: mongo1
        hostname: mongo1
        image: mongo:6
        volumes:
            - ../../database/.tmp-data/spot-share-data1:/data/db
        networks:
            - spot-share-network
        ports:
            - 27017:27017
        links:
            - mongo2
            - mongo3
        depends_on:
            - mongo2
            - mongo3
        restart: always
        entrypoint: ['mongod', '--replSet', 'myReplicaSet', '--bind_ip', 'localhost,mongo1']

    mongo2:
        container_name: mongo2
        hostname: mongo2
        image: mongo:6
        volumes:
            - ../../database/.tmp-data/spot-share-data2:/data/db
        networks:
            - spot-share-network
        ports:
            - 27018:27017
        restart: always
        entrypoint: ['mongod', '--replSet', 'myReplicaSet', '--bind_ip', 'localhost,mongo2']

    mongo3:
        container_name: mongo3
        hostname: mongo3
        image: mongo:6
        volumes:
            - ../../database/.tmp-data/spot-share-data3:/data/db
        networks:
            - spot-share-network
        ports:
            - 27019:27017
        restart: always
        entrypoint: ['mongod', '--replSet', 'myReplicaSet', '--bind_ip', 'localhost,mongo3']

    mongosetup:
        image: mongo:6
        depends_on:
            - mongo1
            - mongo2
            - mongo3
        volumes:
            - ./scripts:/scripts
        networks:
            - spot-share-network
        restart: 'no'
        entrypoint: ['bash', '/scripts/mongo_setup.sh']

networks:
    spot-share-network:
        driver: bridge
