---
version: '3.7'
networks:
    emaily-user-feedback-network:
        driver: bridge
services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../backend/services/emaily-user-feedback-proxy
            dockerfile: dev.Dockerfile
        container_name: container-emaily-user-feedback-proxy
        image: paulserbandev/emaily-user-feedback-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../backend/services/emaily-user-feedback-proxy/default.conf:/etc/nginx/conf.d/default.conf
            - ../../backend/services/emaily-user-feedback-proxy/logs:/var/log/nginx
        networks:
            - emaily-user-feedback-network
    # ---------------------------------------------------------------------
    # | ExpressJS API                                                     |
    # ---------------------------------------------------------------------
    express-emaily-user-feedback-api:
        build:
            context: ../../backend/api/emaily-user-feedback-api
            dockerfile: dev.Dockerfile
        image: paulserbandev/emaily-user-feedback-api
        container_name: container-emaily-user-feedback-api
        restart: always
        volumes:
            - ../../backend/api/emaily-user-feedback-api:/usr/src/app/
            - /usr/src/app/node_modules
        networks:
            - emaily-user-feedback-network
