---
version: '3.8'

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        build:
            context: ../../backend/middleware/events-showcase-proxy
            dockerfile: dev.Dockerfile
        container_name: container-events-showcase-proxy
        image: paulserbandev/events-showcase-proxy
        restart: unless-stopped
        ports:
            - '3000:80'
        volumes:
            - ../../backend/middleware/events-showcase-proxy/default.conf:/etc/nginx/conf.d/default.conf
            - ../../backend/middleware/events-showcase-proxy/logs:/var/log/nginx
        networks:
            - events-showcase-network
    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        container_name: ui-react-spa-container
        build:
            context: ../../frontend/apps/events-showcase-app
            dockerfile: dev.Dockerfile
        volumes:
            - ../../frontend/apps/events-showcase-app:/usr/src/app # Mount the app directory to the container
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
        env_file:
            - ../../infrastructure/env/events-showcase.compose.env
        networks:
            - events-showcase-network

    # ---------------------------------------------------------------------
    # | ExpressJS API                                                     |
    # ---------------------------------------------------------------------
    express-events-showcase-api:
        build:
            context: ../../backend/api/events-showcase-api
            dockerfile: dev.Dockerfile
        image: paulserbandev/events-showcase-api
        container_name: container-events-showcase-api
        restart: always
        # ensure that the CONTAINER user id and group id are the same as the HOST user id and group id
        # without this, the container will fail to write files to the host volume
        user: '${HOST_USER_ID}:${HOST_GROUP_ID}'
        env_file:
            - ../../infrastructure/env/events-showcase.compose.env
            - ../../.env
        volumes:
            - ../../backend/api/events-showcase-api:/usr/src/app/
            - /usr/src/app/node_modules
        networks:
            - events-showcase-network

networks:
    events-showcase-network:
        driver: bridge
