---
version: '3.8'

services:
    # ---------------------------------------------------------------------
    # | UI React SP                                                       |
    # ---------------------------------------------------------------------
    frontend:
        build:
            context: ../../frontend/apps/to-do-app
            dockerfile: dev.Dockerfile
        container_name: react-app
        ports:
            - '5173:5173'
        stdin_open: true
        tty: true
        depends_on:
            - backend
        networks:
            - to-do-networks

    # ---------------------------------------------------------------------
    # | Node.js API                                                       |
    # ---------------------------------------------------------------------
    backend:
        build:
            context: ../../backend/api/to-do-api
            dockerfile: dev.Dockerfile
        container_name: node-api
        ports:
            - '3000:3000'
        restart: always
        environment:
            - DB_ATLAS_URI=${DB_ATLAS_URI}
            - DB_LOCAL_URI=${DB_LOCAL_URI}
            - MONGO_USERNAME=${MONGO_USERNAME}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - MONGO_HOSTNAME=${MONGO_HOSTNAME}
            - MONGO_PORT=${MONGO_PORT}
            - MONGO_DB=${MONGO_DB}
            - NODE_ENV=${NODE_ENV}
        depends_on:
            - database
        networks:
            - to-do-networks

    # ---------------------------------------------------------------------
    # | MongoDB Database                                                   |
    # ---------------------------------------------------------------------
    database:
        image: mongo
        container_name: mongo-db
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        networks:
            - to-do-networks

networks:
    to-do-networks:
        driver: bridge
