FROM wbk--mern-playground__core:latest as builder
COPY ./backend/api/filtered-gallery-api ./backend/api/filtered-gallery-api
RUN yarn install
RUN yarn build:filtered-gallery-api

FROM node:20-alpine as service

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/backend/api/filtered-gallery-api/package.json ./
COPY --from=builder /usr/src/app/backend/api/filtered-gallery-api/dist ./dist

RUN yarn install --production

CMD ["node", "./dist/bin/www.js"]