FROM wbk--mern-playground__core:latest as builder

COPY ./backend/services/dj-events-ssr-service ./backend/services/dj-events-ssr-service

ARG PORT
ARG PROTOCOL
ARG HOSTNAME
ARG API_URL
ARG APP_URL
ARG CMS_URL

ENV PORT=$PORT

ENV NEXT_PUBLIC_PROTOCOL=$PROTOCOL
ENV NEXT_PUBLIC_HOSTNAME=$HOSTNAME
ENV NEXT_PUBLIC_PORT=$PORT

ENV NEXT_PUBLIC_APP_URL=$APP_URL
ENV NEXT_PUBLIC_API_URL=$API_URL

ENV NEXT_PUBLIC_CMS_URL=$CMS_URL

EXPOSE $PORT

RUN yarn install

CMD [ "yarn", "develop:dj-events-ssr-service"]