FROM wbk--mern-playground__core:latest as builder

COPY ./frontend/sites/flowrise-site ./frontend/sites/flowrise-site

ARG CONTAINER_PORT
ENV PORT=$CONTAINER_PORT
EXPOSE $CONTAINER_PORT

RUN yarn install

CMD [ "yarn", "develop:flowrise-site"]