FROM wordpress:latest

COPY ./backend/services/ssr/hello-wordpress-ssr-service/src/wp-content /usr/src/wordpress/wp-content

# do not install this on production images
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

RUN rm -rf /var/lib/apt/lists/* \
  && mkdir -p /var/www/html/wp-content \
  && chown -R www-data:www-data /var/www/html/wp-content
