FROM wbk--mern-playground__core:latest as builder

COPY ./backend/api/devcamper-api ./backend/api/devcamper-api

ARG CONTAINER_PORT
ENV PORT=$CONTAINER_PORT
EXPOSE $CONTAINER_PORT

RUN yarn install

CMD [ "yarn", "develop:devcamper-api"]