FROM wbk--mern-playground__core:latest as builder

COPY ./frontend/apps/emaily-user-feedback-app ./frontend/apps/emaily-user-feedback-app

ARG CONTAINER_PORT
ENV PORT=$CONTAINER_PORT
EXPOSE $CONTAINER_PORT

RUN yarn install

# NOTE: this script is available in the base image
CMD [ "yarn", "develop:emaily-user-feedback-app"]