FROM wbk--mern-playground__core:latest as builder
COPY ./frontend/apps/emaily-user-feedback-app ./frontend/apps/emaily-user-feedback-app
RUN yarn install
RUN yarn build:emaily-user-feedback-app

FROM nginx:latest as prod
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log
COPY --from=builder /usr/src/app/frontend/apps/emaily-user-feedback-app/dist /usr/share/nginx/html
COPY ./frontend/apps/emaily-user-feedback-app/nginx/default.conf /etc/nginx/conf.d/default.conf