FROM wbk--mern-playground__core:latest as builder
COPY ./frontend/sites/devcamper-site ./frontend/sites/devcamper-site
COPY ./assets/devcamper-assets ./assets/devcamper-assets
RUN yarn install
RUN yarn process:devcamper-assets
RUN yarn build:devcamper-site

FROM nginx:latest as server
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log
COPY --from=builder /usr/src/app/frontend/sites/devcamper-site/dist /usr/share/nginx/html
COPY --from=builder /usr/src/app/assets/devcamper-assets/dist /usr/share/nginx/html/assets
COPY ./frontend/sites/devcamper-site/config/default.conf /etc/nginx/conf.d/default.conf