---
name: Develop Frontend NextJS SSG Portfolio Website

on:
  push:
    branches-ignore:
      - release
      - main
      - develop

  pull_request:
    types: [synchronize]

  workflow_dispatch:

jobs:
  build-frontend:
    name: Build Frontend NextJS SSG Portfolio Website
    runs-on: ubuntu-latest
    env:
      ASSETS_ROOT: assets
      FE_NEXTJS_PROJECT_ROOT: frontend/portfolio-website-nextjs
      NODE_VERSION: 16.19.0
      SITE_URL: https://paulalexserban.github.io/prj--personal-portfolio
    steps:
      - name: "📥  Checkout repository"
        uses: actions/checkout@v3

      - name: "🔍  Verify Changed Files"
        uses: tj-actions/changed-files@v35
        id: changed-frontend-portfolio-website-files
        with:
          files: ${{ env.FE_NEXTJS_PROJECT_ROOT }}/**/*

      - name: "🔄  Cache node_modules"
        if: ${{ always() }}
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: "🔧  Setup NodeJS ${{ env.NODE_VERSION }}"
        if: ${{ always() }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "🔧  Install npm@latest & CI Deps"
        if: ${{ always() }}
        run: |
          npm i -g npm@latest
          npm ci

      #   @INFO - this part is needed when assets module will be functional
      # - name: "Install GraphicsMagick"
      #   if: ${{ steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true' }}
      #   run: sudo apt-get install -y graphicsmagick

      - name: "📦  Install Frontend NextJS Portfolio Website dependencies"
        if: ${{ steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true' }}
        run: |
          bash scripts/modulize.bash -e prod -p install -m portfolio-website-nextjs

      - name: "🔍  Lint Frontend NextJS SSG Portfolio Website"
        if: ${{ steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true' }}
        run: |
          bash scripts/modulize.bash -e prod -p lint -m portfolio-website-nextjs
        continue-on-error: true

      - name: "🏗️  Build Frontend NextJS SSG Portfolio Website For GitHub Pages"
        if: ${{ steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true' }}
        run: |
          bash scripts/modulize.bash -e gh_pages -p build -m portfolio-website-nextjs

      - name: "🚚  Package NextJS Portfolio Website"
        if: ${{ steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true' }}
        run: |
          bash scripts/modulize.bash -e prod -p package -m portfolio-website-nextjs

      - name: "Configure git"
        run: |
          git config --global user.email "paul.alex.serban@gmail.com"
          git config --global user.name "paulAlexSerban"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

      - name: "🚀 Deploy to Test (GitHub Pages)"
        if: ${{ steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true' }}
        run: npx gh-pages -d package/portfolio-website-nextjs --branch gh-pages-test -t true